{
  imports = [
    ./cmp.nix
    ./colors.nix
    ./conform.nix
    ./copilot.nix
    ./dap.nix
    ./gitsigns.nix
    ./lsp.nix
    ./luasnip.nix
    ./mini.nix
    ./neo-tree.nix
    ./neogit.nix
    ./notify.nix
    ./remap.nix
    ./resession.nix
    ./set.nix
    ./telescope.nix
    ./treesitter.nix
    ./trouble.nix
  ];
}
